device: "mps"
num_workers: 0
log: False
wandb_project: my_project

random_seed: 0
random_seed_data: 123
val_interval: 10
num_epochs: 1

defaults:
  - _self_
  - algorithm: supervised_classification
  - dataset: dummy
